# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-08 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0010_order_ordergoods'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='number',
            new_name='identifier',
        ),
        migrations.AlterField(
            model_name='order',
            name='createtime',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
