# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-08 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0011_auto_20181108_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
